var annotated_dup =
[
    [ "jas_allocator_s", "structjas__allocator__s.html", "structjas__allocator__s" ],
    [ "jas_cmclrspcconv_t", "structjas__cmclrspcconv__t.html", null ],
    [ "jas_cmcmptfmt_t", "structjas__cmcmptfmt__t.html", null ],
    [ "jas_cmpixmap_t", "structjas__cmpixmap__t.html", null ],
    [ "jas_cmprof_t", "structjas__cmprof__t.html", null ],
    [ "jas_cmpxform_s", "structjas__cmpxform__s.html", null ],
    [ "jas_cmpxformops_t", "structjas__cmpxformops__t.html", null ],
    [ "jas_cmpxformseq_t", "structjas__cmpxformseq__t.html", null ],
    [ "jas_cmshaplut_t", "structjas__cmshaplut__t.html", null ],
    [ "jas_cmshapmat_t", "structjas__cmshapmat__t.html", null ],
    [ "jas_cmshapmatlut_t", "structjas__cmshapmatlut__t.html", null ],
    [ "jas_cmxform_t", "structjas__cmxform__t.html", null ],
    [ "jas_image_cmpt_t", "structjas__image__cmpt__t.html", null ],
    [ "jas_image_cmptparm_t", "structjas__image__cmptparm__t.html", null ],
    [ "jas_image_fmt_t", "structjas__image__fmt__t.html", "structjas__image__fmt__t" ],
    [ "jas_image_fmtinfo_t", "structjas__image__fmtinfo__t.html", "structjas__image__fmtinfo__t" ],
    [ "jas_image_fmtops_t", "structjas__image__fmtops__t.html", "structjas__image__fmtops__t" ],
    [ "jas_image_t", "structjas__image__t.html", null ],
    [ "jas_logtype_t", "structjas__logtype__t.html", null ],
    [ "jas_matrix_t", "structjas__matrix__t.html", null ],
    [ "jas_opt_t", "structjas__opt__t.html", null ],
    [ "jas_std_allocator_t", "structjas__std__allocator__t.html", null ],
    [ "jas_stream_t", "structjas__stream__t.html", null ],
    [ "jas_taginfo_t", "structjas__taginfo__t.html", null ],
    [ "jas_tvparser_t", "structjas__tvparser__t.html", null ]
];